//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.08.05 at 11:10:00 AM IST 
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "http://techbd.org/hello", elementFormDefault = jakarta.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.techbd.hello;
