org:
  techbd:
    version: ${project.version}
    baseFHIRURL: ${TECHBD_BASE_FHIR_URL} #This is the default FHIR url used in generating FHIR from CSV
    csv:
      validation:
        pythonScriptPath: ${TECHBD_PYTHON_SCRIPT_PATH}support/specifications/flat-file/validate-nyher-fhir-ig-equivalent.py
        pythonExecutable: python3
        packagePath: ${TECHBD_PYTHON_SCRIPT_PATH}support/specifications/flat-file/datapackage-nyher-fhir-ig-equivalent.json
        inboundPath: /app/techbyDesign/flatFile/inbound
        outputPath: /app/techbyDesign/flatFile/outbound
        ingressHomePath: /app/techbyDesign/flatFile/ingress
    udi:
      prime:
        jdbc:
          # JDBC connection settings for the UDI Prime database
          # The environment variable ${SPRING_PROFILES_ACTIVE} should be set to the active profile (e.g., dev, qa, prod)
          # This allows for different configurations based on the active profile
          # Example: If SPRING_PROFILES_ACTIVE=dev, then the property will resolve to dev_TECHBD_UDI_DS_PRIME_JDBC_URL
          url: ${${SPRING_PROFILES_ACTIVE}_TECHBD_UDI_DS_PRIME_JDBC_URL:}
          jdbcUrl: ${${SPRING_PROFILES_ACTIVE}_TECHBD_UDI_DS_PRIME_JDBC_URL:}
          username: ${${SPRING_PROFILES_ACTIVE}_TECHBD_UDI_DS_PRIME_JDBC_USERNAME:}
          password: ${${SPRING_PROFILES_ACTIVE}_TECHBD_UDI_DS_PRIME_JDBC_PASSWORD:}
          driverClassName: org.postgresql.Driver
          maximumPoolSize: 10   # The maximum number of database connections HikariCP can open simultaneously. 
                      # For Aurora instances, a common guideline is: vCPUs × 2 + a small overhead 
                      # (e.g., for a 2-vCPU Aurora instance → recommended range is ~8–10).
          minimumIdle: 5                # Minimum number of idle connections kept ready (half of maxPoolSize)
          idleTimeout: 60000            # 1 minute – aggressively removes idle connections to avoid unnecessary DB load
          connectionTimeout: 20000      # 20 seconds to wait for a connection from the pool before timing out
          maxLifetime: 1800000          # 30 minutes – maximum lifetime before a connection is replaced (safe for Aurora)
    dataLedgerApiUrl: ${TECHBD_DATA_LEDGER_API_URL}
    dataLedgerApiKeySecretName: techbd-nyec-dataledger-api-key
    dataLedgerTracking: ${TECHBD_DATA_LEDGER_TRACKING_ENABLED:false}
    dataLedgerDiagnostics: ${TECHBD_DATA_LEDGER_DIAGNOSTICS_ENABLED:true}
    validation-severity-level: error  # Possible values: fatal, error, warning, information
    structureDefinitionsUrls:
      bundle: /StructureDefinition/SHINNYBundleProfile
      patient: /StructureDefinition/shinny-patient
      consent: /StructureDefinition/shinny-Consent
      encounter: /StructureDefinition/shinny-encounter
      organization: /StructureDefinition/shin-ny-organization
      observation: /StructureDefinition/shinny-observation-screening-response
      questionnaire: /StructureDefinition/shinny-questionnaire
      practitioner: /StructureDefinition/shin-ny-practitioner
      questionnaireResponse: /StructureDefinition/shinny-questionnaire
      observationSexualOrientation: /StructureDefinition/shinny-observation-sexual-orientation
      procedure: /StructureDefinition/shinny-sdoh-procedure
spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
      file-size-threshold: 2MB
      resolve-lazily: true