org:
  techbd:    
    service:
      http:
        interactions:
          defaultPersistStrategy: "{ \"nature\": \"fs\" }"
          saveUserDataToInteractions: true
        hub:
          prime:
            postStdinPayloadToNyecDataLakeExternal:
              # The command requires tenantId as argument 1 and payload via STDIN
              # The command will return a status as a normal process and STDOUT will include all verbose debugging
              #cmd: support/bin/post-stdin-payload-to-nyec-datalake-qa-endpoint-via-mtls.sh
              cmd: ../support/bin/post-stdin-payload-to-nyec-datalake-qa-endpoint-sandbox-test.sh
              # Wait time to receive response from scoring engine
              timeout: 180

management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: actuator,beans,env,openapi,swagger-ui,health,info,metrics
  health:
    db:
      enabled: true
  endpoint:
    beans:
      enabled: true
    env:
      enabled: true
      show-values: always
    health:
      enabled: true
      show-details: always
    info:
      enabled: true
    metrics:
      enabled: true
    prometheus:
      enabled: true
  info:
    git:
      mode: full
    build:
      enabled: true
    env:
      enabled: true
    java:
      enabled: true
    os:
      enabled: true
       