@startuml IE
  hide circle
  skinparam linetype ortho
  skinparam roundcorner 20
  skinparam class {
    BackgroundColor White
    ArrowColor Silver
    BorderColor Silver
    FontColor Black
    FontSize 12
  }

  entity "hub_device" as hub_device {
    * **hub_device_id**: TEXT
    --
    * key: TEXT
      created_at: TIMESTAMPTZ
    * created_by: TEXT
    * provenance: TEXT
  }

  entity "sat_device_device" as sat_device_device {
    * **sat_device_device_id**: TEXT
    --
    * hub_device_id: TEXT
    * name: TEXT
    * state: TEXT
    * boundary: TEXT
      segmentation: TEXT
      state_sysinfo: TEXT
      elaboration: JSONB
      created_at: TIMESTAMPTZ
    * created_by: TEXT
    * provenance: TEXT
  }

  entity "hub_request_http_client" as hub_request_http_client {
    * **hub_request_http_client_id**: TEXT
    --
    * key: TEXT
      created_at: TIMESTAMPTZ
    * created_by: TEXT
    * provenance: TEXT
  }

  entity "sat_request_http_client_meta_data" as sat_request_http_client_meta_data {
    * **sat_request_http_client_meta_data_id**: TEXT
    --
    * hub_request_http_client_id: TEXT
      request_payload: JSONB
      elaboration: JSONB
      created_at: TIMESTAMPTZ
    * created_by: TEXT
    * provenance: TEXT
  }

  entity "hub_ingest_session" as hub_ingest_session {
    * **hub_ingest_session_id**: TEXT
    --
    * key: TEXT
      created_at: TIMESTAMPTZ
    * created_by: TEXT
    * provenance: TEXT
  }

  entity "hub_ingest_session_entry" as hub_ingest_session_entry {
    * **hub_ingest_session_entry_id**: TEXT
    --
    * key: TEXT
      created_at: TIMESTAMPTZ
    * created_by: TEXT
    * provenance: TEXT
  }

  entity "sat_ingest_session_meta_data" as sat_ingest_session_meta_data {
    * **sat_ingest_session_meta_data_id**: TEXT
    --
    * hub_ingest_session_id: TEXT
    * device_id: TEXT
    * version: TEXT
    * orch_started_at: DATE
    * orch_finished_at: DATE
    * qe_identifier: TEXT
    * content_hash: TEXT
      args_json: JSONB
      diagnostics_json: JSONB
      diagnostics_md: TEXT
      elaboration: JSONB
      created_at: TIMESTAMPTZ
    * created_by: TEXT
    * provenance: TEXT
  }

  entity "sat_ingest_session_entry_payload" as sat_ingest_session_entry_payload {
    * **sat_ingest_session_entry_payload_id**: TEXT
    --
    * hub_ingest_session_entry_id: TEXT
    * ingest_src: TEXT
      ingest_table_name: TEXT
      ingest_payload: JSONB
      elaboration: JSONB
      created_at: TIMESTAMPTZ
    * created_by: TEXT
    * provenance: TEXT
  }

  entity "sat_ingest_session_entry_session_state" as sat_ingest_session_entry_session_state {
    * **sat_ingest_session_entry_session_state_id**: TEXT
    --
    * hub_ingest_session_entry_id: TEXT
    * from_state: TEXT
    * to_state: TEXT
      transition_result: TEXT
      transition_reason: TEXT
      elaboration: JSONB
      created_at: TIMESTAMPTZ
    * created_by: TEXT
    * provenance: TEXT
  }

  entity "sat_ingest_session_entry_session_exec" as sat_ingest_session_entry_session_exec {
    * **sat_ingest_session_entry_session_exec_id**: TEXT
    --
    * hub_ingest_session_entry_id: TEXT
    * exec_nature: TEXT
      parent_exec_id: TEXT
      namespace: TEXT
      exec_identity: TEXT
    * exec_code: TEXT
    * exec_status: INTEGER
      input_text: TEXT
      exec_error_text: TEXT
      output_text: TEXT
      output_nature: TEXT
      narrative_md: TEXT
      elaboration: JSONB
      created_at: TIMESTAMPTZ
    * created_by: TEXT
    * provenance: TEXT
  }

  entity "sat_ingest_session_entry_session_issue" as sat_ingest_session_entry_session_issue {
    * **sat_ingest_session_entry_session_issue_id**: TEXT
    --
    * hub_ingest_session_entry_id: TEXT
    * issue_type: TEXT
    * issue_message: TEXT
    * level: TEXT
      issue_column: INTEGER
      issue_row: INTEGER
      message_id: TEXT
    * ignorableError: BOOLEAN
      invalid_value: TEXT
      comment: TEXT
      display: TEXT
      disposition: TEXT
      remediation: TEXT
      validation_engine_payload: JSONB
      elaboration: JSONB
      created_at: TIMESTAMPTZ
    * created_by: TEXT
    * provenance: TEXT
  }

  entity "link_session_request" as link_session_request {
    * **link_session_request_id**: TEXT
    --
    * hub_ingest_session_id: TEXT
    * hub_request_http_client_id: TEXT
      created_at: TIMESTAMPTZ
    * created_by: TEXT
    * provenance: TEXT
  }

  entity "link_session_entry" as link_session_entry {
    * **link_session_entry_id**: TEXT
    --
    * hub_ingest_session_id: TEXT
    * hub_ingest_session_entry_id: TEXT
      created_at: TIMESTAMPTZ
    * created_by: TEXT
    * provenance: TEXT
  }

  entity "link_session_device" as link_session_device {
    * **link_session_device_id**: TEXT
    --
    * hub_ingest_session_id: TEXT
    * hub_device_id: TEXT
      created_at: TIMESTAMPTZ
    * created_by: TEXT
    * provenance: TEXT
  }

  entity "hub_exception" as hub_exception {
    * **hub_exception_id**: TEXT
    --
      key: TEXT
      created_at: TIMESTAMPTZ
    * created_by: TEXT
    * provenance: TEXT
  }

  entity "sat_exception_diagnostics" as sat_exception_diagnostics {
    * **sat_exception_diagnostics_id**: TEXT
    --
    * hub_exception_id: TEXT
    * message: TEXT
    * err_returned_sqlstate: TEXT
    * err_pg_exception_detail: TEXT
    * err_pg_exception_hint: TEXT
    * err_pg_exception_context: TEXT
      created_at: TIMESTAMPTZ
    * created_by: TEXT
    * provenance: TEXT
  }

  entity "sat_exception_http_client" as sat_exception_http_client {
    * **sat_exception_http_client_id**: TEXT
    --
    * hub_exception_id: TEXT
      http_req: JSONB
      http_resp: JSONB
      elaboration: JSONB
      created_at: TIMESTAMPTZ
    * created_by: TEXT
    * provenance: TEXT
  }

  hub_device |o..o{ sat_device_device
  hub_request_http_client |o..o{ sat_request_http_client_meta_data
  hub_ingest_session |o..o{ sat_ingest_session_meta_data
  hub_ingest_session_entry |o..o{ sat_ingest_session_entry_payload
  hub_ingest_session_entry |o..o{ sat_ingest_session_entry_session_state
  hub_ingest_session_entry |o..o{ sat_ingest_session_entry_session_exec
  hub_ingest_session_entry |o..o{ sat_ingest_session_entry_session_issue
  hub_ingest_session |o..o{ link_session_request
  hub_request_http_client |o..o{ link_session_request
  hub_ingest_session |o..o{ link_session_entry
  hub_ingest_session_entry |o..o{ link_session_entry
  hub_ingest_session |o..o{ link_session_device
  hub_device |o..o{ link_session_device
  hub_exception |o..o{ sat_exception_diagnostics
  hub_exception |o..o{ sat_exception_http_client
@enduml
