-- use explicit schema, not search_path (see README.md)
CREATE EXTENSION IF NOT EXISTS pgtap SCHEMA techbd_udi_assurance;

--BEGIN;

-- Test for fn_hub_device_upserted
--SELECT plan(5);

--SELECT * FROM runtests('techbd_udi_assurance'::name, 'test_hub_device_upserted');
--SELECT * FROM runtests('techbd_udi_assurance'::name, 'test_hub_ingest_session_entry_upserted');
--SELECT * FROM runtests('techbd_udi_assurance'::name, 'test_hub_ingest_session_upserted');
--SELECT * FROM runtests('techbd_udi_assurance'::name, 'test_hub_request_http_client_upserted');
--SELECT * FROM runtests('techbd_udi_assurance'::name, 'test_hub_exception_upserted');
--SELECT * FROM runtests('techbd_udi_assurance'::name, 'test_sat_device_upserted');
--SELECT * FROM runtests('techbd_udi_assurance'::name, 'test_sat_exception_diagnostics_upserted');
--SELECT * FROM runtests('techbd_udi_assurance'::name, 'test_sat_ingest_session_entry_session_exec_upserted');
--SELECT * FROM runtests('techbd_udi_assurance'::name, 'test_sat_ingest_session_entry_session_issue_upserted');
--SELECT * FROM runtests('techbd_udi_assurance'::name, 'test_sat_ingest_session_entry_session_issue_upserted');
--SELECT * FROM runtests('techbd_udi_assurance'::name, 'test_sat_ingest_session_entry_session_state_upserted');
--SELECT * FROM runtests('techbd_udi_assurance'::name, 'test_sat_ingest_session_upserted');
--SELECT * FROM runtests('techbd_udi_assurance'::name, 'test_sat_request_http_client_meta_data_upserted');
--SELECT * FROM runtests('techbd_udi_assurance'::name, 'test_link_session_device_upserted');
--SELECT * FROM runtests('techbd_udi_assurance'::name, 'test_link_session_entry_upserted');
--SELECT * FROM runtests('techbd_udi_assurance'::name, 'test_link_session_request_upserted;
--SELECT * FROM runtests('techbd_udi_assurance'::name, 'test_udi_insert_session_with_state');

--SELECT * FROM finish();

--COMMIT;
