
org:
  techbd:
    baseFHIRURL: http://shinny.org/us/ny/hrsn #This is the default FHIR url used in generating FHIR from CSV
    dataLedgerApiUrl: https://6z5cce0m4h.execute-api.us-east-1.amazonaws.com/production/DataLedger 
    dataLedgerTracking: true
    dataLedgerDiagnostics: true
    dataLedgerApiKeySecretName: techbd-nyec-dataledger-api-key