org:
  techbd:
    aws:
      region: us-east-1
      access-key: test
      secret-key: test
      s3:
        default-config:
          bucket: local-sbx-nexus-ingestion-s3-bucket
          metadata-bucket: local-sbx-nexus-ingestion-s3-metadata-bucket
          endpoint: http://localhost:4566
        hold-config:
          bucket: local-pdr-txd-sbx-hold
          metadata-bucket: local-sbx-nexus-ingestion-s3-metadata-bucket
          endpoint: http://localhost:4566
      sqs:
        endpoint: http://localhost:4566
        base-url: http://localhost:4566/000000000000
        fifo-queue-url: http://localhost:4566/000000000000/txd-sbx-main-queue.fifo

