name: Polyglot Prime CI/CD Pipeline
on:
  # Runs on releases
  release:
    types: [published]
# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages 
permissions:
  contents: write
  pages: write
  id-token: write
# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false
jobs:
    synthetic-techbd-devl-deployment:
      runs-on: ubuntu-latest
      if: "!endsWith(github.event.release.tag_name, '-nexus')"
      steps:
        - uses: actions/checkout@v4

        - name: Configure Git
          run: |
            git config --global user.email "action@github.com"
            git config --global user.name "GitHub Action"
  
        - name: Clone infrastructure repository
          run: |
            git clone https://${{ secrets.ACTIONS_GITHUB_TOKEN }}@github.com/tech-by-design/infrastructure-prime.git

        - name: Create and switch to a new branch
          run: |
            cd infrastructure-prime
            git checkout -b synthetic-techbd-fhir-development-${{ github.ref_name}}-deployment
            
        - name: Update fhir environment file
          run: |
            cd infrastructure-prime
            sed -i 's/TAG=.*/TAG=${{ github.ref_name }}/g' aws/synthetic.fhir.api.qualifiedentity.org/.env
  
        - name: Commit and push changes
          run: |
            cd infrastructure-prime
            git add .
            git commit -m "ci: fhir development ${{ github.ref_name }} deployment"
            git push --set-upstream origin synthetic-techbd-fhir-development-${{ github.ref_name}}-deployment

        - name: Create Pull Request
          env:
            GH_TOKEN: ${{ secrets.ACTIONS_GITHUB_TOKEN }}
          run: |
            cd infrastructure-prime
            gh pr create --base main --head synthetic-techbd-fhir-development-${{ github.ref_name}}-deployment --title "FHIR Devl techbd.org ${{ github.ref_name }} update" --body "Automated techbd fhir devl deployment for version ${{ github.ref_name }}"

    synthetic-techbd-stage-deployment:
      runs-on: ubuntu-latest
      if: "!endsWith(github.event.release.tag_name, '-nexus')"
      steps:
        - uses: actions/checkout@v4

        - name: Configure Git
          run: |
            git config --global user.email "action@github.com"
            git config --global user.name "GitHub Action"
  
        - name: Clone infrastructure repository
          run: |
            git clone https://${{ secrets.ACTIONS_GITHUB_TOKEN }}@github.com/tech-by-design/infrastructure-prime.git

        - name: Create and switch to a new branch
          run: |
            cd infrastructure-prime
            git checkout -b synthetic-techbd-fhir-stage-${{ github.ref_name}}-deployment

        - name: Update fhir environment file
          run: |
            cd infrastructure-prime
            sed -i 's/TAG=.*/TAG=${{ github.ref_name }}/g' aws/synthetic.fhir.api.stage.techbd.org/.env
  
        - name: Commit and push changes
          run: |
            cd infrastructure-prime
            git add .
            git commit -m "ci: fhir staging ${{ github.ref_name }} deployment"
            git push --set-upstream origin synthetic-techbd-fhir-stage-${{ github.ref_name}}-deployment

        - name: Create Pull Request
          env:
            GH_TOKEN: ${{ secrets.ACTIONS_GITHUB_TOKEN }}
          run: |
            cd infrastructure-prime
            gh pr create --base main --head synthetic-techbd-fhir-stage-${{ github.ref_name}}-deployment --title "FHIR stage techbd.org ${{ github.ref_name }} update" --body "Automated techbd fhir stage deployment for version ${{ github.ref_name }}"  


    phi-prod-techbd-deployment:
      runs-on: ubuntu-latest
      if: "!endsWith(github.event.release.tag_name, '-nexus')"
      steps:
        - uses: actions/checkout@v4

        - name: Configure Git
          run: |
            git config --global user.email "action@github.com"
            git config --global user.name "GitHub Action"
  
        - name: Clone infrastructure repository
          run: |
            git clone https://${{ secrets.ACTIONS_GITHUB_TOKEN }}@github.com/tech-by-design/infrastructure-prime.git
            
        - name: Create and switch to a new branch
          run: |
            cd infrastructure-prime
            git checkout -b phi-prod-techbd-fhir-${{ github.ref_name}}-deployment
            
        - name: Update fhir environment file
          run: |
            cd infrastructure-prime
            sed -i 's/TAG=.*/TAG=${{ github.ref_name }}/g' aws/hub.techbd.org/.env
  
        - name: Commit and push changes
          run: |
            cd infrastructure-prime
            git add .
            git commit -m "ci: fhir production ${{ github.ref_name }} deployment"
            git push --set-upstream origin phi-prod-techbd-fhir-${{ github.ref_name}}-deployment
  
        - name: Create Pull Request
          env:
            GH_TOKEN: ${{ secrets.ACTIONS_GITHUB_TOKEN }}
          run: |
            cd infrastructure-prime
            gh pr create --base main --head phi-prod-techbd-fhir-${{ github.ref_name}}-deployment --title "FHIR prod techbd.org ${{ github.ref_name }} update" --body "Automated techbd fhir prod deployment for version ${{ github.ref_name }}"

    phi-qa-techbd-deployment:
      runs-on: ubuntu-latest
      if: "!endsWith(github.event.release.tag_name, '-nexus')"
      steps:
        - uses: actions/checkout@v4

        - name: Configure Git
          run: |
            git config --global user.email "action@github.com"
            git config --global user.name "GitHub Action"
  
        - name: Clone infrastructure repository
          run: |
            git clone https://${{ secrets.ACTIONS_GITHUB_TOKEN }}@github.com/tech-by-design/infrastructure-prime.git
            
        - name: Create and switch to a new branch
          run: |
            cd infrastructure-prime
            git checkout -b phi-qa-techbd-fhir-${{ github.ref_name}}-deployment
            
        - name: Update fhir environment file
          run: |
            cd infrastructure-prime
            sed -i 's/TAG=.*/TAG=${{ github.ref_name }}/g' aws/phi.hub.qa.techbd.org/.env
  
        - name: Commit and push changes
          run: |
            cd infrastructure-prime
            git add .
            git commit -m "ci: fhir phi qa ${{ github.ref_name }} deployment"
            git push --set-upstream origin phi-qa-techbd-fhir-${{ github.ref_name}}-deployment
  
        - name: Create Pull Request
          env:
            GH_TOKEN: ${{ secrets.ACTIONS_GITHUB_TOKEN }}
          run: |
            cd infrastructure-prime
            gh pr create --base main --head phi-qa-techbd-fhir-${{ github.ref_name}}-deployment --title "FHIR PHI QA techbd.org ${{ github.ref_name }} update" --body "Automated techbd fhir phi qa deployment for version ${{ github.ref_name }}"
